msys2-runtime: Add patches that support for build as cygwin1.dll or msys-2.0.dll
migrating msys2-runtime to cygwin

msys2-runtime commit-id for cygwin1.dll is from:
https://github.com/lygstate/msys2-runtime/commit/fd5ce305d44723feb3e60c927295d5973ee7692b

The commit-id for msys-2.0.dll and cygwin1.dll should not be the same.
So that they can call each other properly

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

diff --git a/msys2-runtime/PKGBUILD b/msys2-runtime/PKGBUILD
--- a/msys2-runtime/PKGBUILD
+++ b/msys2-runtime/PKGBUILD
@@ -30,6 +30,31 @@ makedepends=('cocom'
 # re zipman: https://github.com/msys2/MSYS2-packages/pull/2687#issuecomment-965714874
 options=('!zipman')
 
+currnent_script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
+source "${currnent_script_dir}/../msys2-runtime/check-bootstrap.sh"
+# _build_as_msys_2_dll==false means build msys2-runtime as cygwin1.dll
+_build_as_msys_2_dll=true
+if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin" ]]; then
+  pkgrel=$pkgrel
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin_hook" ]]; then
+  pkgrel=5
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage0" ]]; then
+  pkgrel=6
+  _build_as_msys_2_dll=false
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage1" ]]; then
+  pkgrel=7
+  _build_as_msys_2_dll=false
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage2" ]]; then
+  pkgrel=8
+  _build_as_msys_2_dll=false
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage3" ]]; then
+  pkgrel=9
+  _build_as_msys_2_dll=false
+else
+ echo "Invalid MSYS_BOOTSTRAP_STAGE: '$MSYS_BOOTSTRAP_STAGE'" >&2
+ exit -1
+fi
+
 _patches=(
   # patches from https://github.com/msys2/msys2-runtime
   0001-Fix-msys-library-name-in-import-libraries.patch
@@ -75,11 +100,49 @@ _patches=(
   0041-Cygwin-console-fix-deadlock-in-pcon-teardown.patch
 )
 
+_patches+=(
+  0067-Revert-strace.cc-Don-t-set-MSYS-noglob.patch
+  0068-Revert-Rename-dll-from-cygwin-to-msys.patch
+  0069-Revert-uname-allow-setting-the-system-name-to-CYGWIN.patch
+  0070-Revert-Add-functionality-for-changing-OS-name-via-MS.patch
+  0071-Add-functionality-for-changing-OS-name-via-MSYSTEM-e.patch
+  0072-Add-support-for-MSYS-environment-variable-instead-of.patch
+  0073-strace.cc-Don-t-set-CYGWIN-noglob.patch
+  0074-Convert-to-use-msys-style-named-pipe.patch
+  0075-Rename-dll-from-cygwin-to-msys.patch
+  0076-hook_or_detect_cygwin-now-use-msys-2.0.dll-instead-o.patch
+  0077-Revert-hook_or_detect_cygwin-now-use-msys-2.0.dll-in.patch
+  0078-Revert-Add-support-for-MSYS-environment-variable-ins.patch
+  0079-Support-for-both-MSYS-and-CYGWIN-environment-variabl.patch
+  0080-hookapi.c-Support-for-both-cygwin-and-msys2-for-boot.patch
+)
+
+# The original msys2-runtime patches that built as msys-2.0.dll
+_patches_exclude_stage_origin=(
+  0077-Revert-hook_or_detect_cygwin-now-use-msys-2.0.dll-in.patch
+  0078-Revert-Add-support-for-MSYS-environment-variable-ins.patch
+  0079-Support-for-both-MSYS-and-CYGWIN-environment-variabl.patch
+  0080-hookapi.c-Support-for-both-cygwin-and-msys2-for-boot.patch
+)
+
+# The original msys2-runtime patches with hookapi and `Support-for-both-MSYS-and-CYGWIN-environment-variable` patches that built as msys-2.0.dll
+# All patches are included.
+_patches_exclude_stage_origin_hook=(
+)
+
+# The new msys2-runtime that built as cygwin1.dll
+_patches_exclude_for_cygwin_dll=(
+  0001-Fix-msys-library-name-in-import-libraries.patch
+  0075-Rename-dll-from-cygwin-to-msys.patch
+)
+
 source=(
   'msys2-runtime'::git://sourceware.org/git/newlib-cygwin.git#tag=cygwin-${pkgver}
 
   ${_patches[@]}
 
+  # The commit-id for msys-2.0.dll and cygwin1.dll should not be the same.
+  msys2-runtime-cygwin1.commit
   msys2-runtime.commit
 )
 
@@ -154,6 +217,25 @@ del_file_exists() {
 }
 # =========================================== #
 
+# Function: exclude_list (list_to_filter, items_to_exclude)
+exclude_list() {
+  local -n arr=$1      # Reference to the main array
+  local -n exclude=$2  # Reference to the exclusion array
+  local -A ex_map      # Associative array for O(1) lookup
+  local result=()
+
+  # Build lookup map from the exclusion list
+  for item in "${exclude[@]}"; do ex_map["$item"]=1; done
+
+  # Filter the main array
+  for item in "${arr[@]}"; do
+      [[ -z "${ex_map[$item]}" ]] && result+=("$item")
+  done
+
+  # Output filtered list (or re-assign to original array if desired)
+  echo "${result[@]}"
+}
+
 prepare() {
   cd "${srcdir}"/msys2-runtime
   if test true != "$(git config core.symlinks)"
@@ -163,6 +245,17 @@ prepare() {
   fi
   del_file_exists winsup/cygwin/msys2_path_conv.cc \
     winsup/cygwin/msys2_path_conv.h
+
+  if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin" ]]; then
+      _patches=($(exclude_list _patches _patches_exclude_stage_origin))
+  elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin_hook" ]]; then
+      _patches=($(exclude_list _patches _patches_exclude_stage_origin_hook))
+  elif [[ "$_build_as_msys_2_dll" == "false" ]]; then
+      _patches=($(exclude_list _patches _patches_exclude_for_cygwin_dll))
+  else
+    echo "Invalid MSYS_BOOTSTRAP_STAGE: '$MSYS_BOOTSTRAP_STAGE'" >&2
+    exit -1
+  fi
 
   for patch_filename in "${_patches[@]}"; do
     apply_git_am_with_msg ${patch_filename}
@@ -191,22 +284,60 @@ build() {
 
   (cd "${srcdir}/msys2-runtime/winsup" && ./autogen.sh)
 
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    msys2_runtime_commit_id=$(cat "${srcdir}/msys2-runtime.commit")
+  else
+    msys2_runtime_commit_id=$(cat "${srcdir}/msys2-runtime-cygwin1.commit")
+  fi
+
   "${srcdir}"/msys2-runtime/configure \
-    --with-msys2-runtime-commit="$(cat "${srcdir}/msys2-runtime.commit")" \
+    --with-msys2-runtime-commit="$msys2_runtime_commit_id" \
     --prefix=/usr \
     --build=${CHOST} \
     --sysconfdir=/etc \
     "${extra_config[@]}"
   LC_ALL=C make
+
+  if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage0" ]]; then
+    cp -af /usr/lib/libmsys-2.0.a /usr/lib/libmsys-2.0.a.origin
+    cp -af /usr/lib/libcygwin.a /usr/lib/libcygwin.a.origin
+    cp -af /usr/lib/libg.a /usr/lib/libg.a.origin
+    cp -af /usr/lib/crt0.o /usr/lib/crt0.o.origin
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/libcygwin.a /usr/lib/libmsys-2.0.a
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/libcygwin.a /usr/lib/libcygwin.a
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/libcygwin.a /usr/lib/libg.a
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/crt0.o /usr/lib/crt0.o
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/gcrt0.o /usr/lib/gcrt0.o
+    find | grep \\.exe$ | xargs -I ARG rm -f ARG
+
+    LC_ALL=C make
+  fi
+
   LC_ALL=C make -j1 DESTDIR="${srcdir}"/dest install
+
+  if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage0" ]]; then
+    cp -af /usr/lib/libmsys-2.0.a.origin /usr/lib/libmsys-2.0.a
+    cp -af /usr/lib/libcygwin.a.origin /usr/lib/libcygwin.a
+    cp -af /usr/lib/libg.a.origin /usr/lib/libg.a
+    cp -af /usr/lib/crt0.o.origin /usr/lib/crt0.o
+    rm /usr/lib/*.origin
+  fi
 
   rm -rf "${srcdir}"/dest/etc
 
-  # split debug info from msys-2.0.dll
-  cd "${srcdir}"/dest
-  objcopy --add-gnu-debuglink=/dev/null --only-keep-debug usr/bin/msys-2.0.dll usr/bin/msys-2.0.dbg
-  objcopy -g --add-gnu-debuglink=usr/bin/msys-2.0.dbg usr/bin/msys-2.0.dll usr/bin/msys-2.0.dll.new
-  mv -f usr/bin/msys-2.0.dll.new usr/bin/msys-2.0.dll
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    # split debug info from msys-2.0.dll
+    cd "${srcdir}"/dest
+    objcopy --add-gnu-debuglink=/dev/null --only-keep-debug usr/bin/msys-2.0.dll usr/bin/msys-2.0.dbg
+    objcopy -g --add-gnu-debuglink=usr/bin/msys-2.0.dbg usr/bin/msys-2.0.dll usr/bin/msys-2.0.dll.new
+    mv -f usr/bin/msys-2.0.dll.new usr/bin/msys-2.0.dll
+  else
+    # split debug info from cygwin1.dll
+    cd "${srcdir}"/dest
+    objcopy --add-gnu-debuglink=/dev/null --only-keep-debug usr/bin/cygwin1.dll usr/bin/cygwin1.dbg
+    objcopy -g --add-gnu-debuglink=usr/bin/cygwin1.dbg usr/bin/cygwin1.dll usr/bin/cygwin1.dll.new
+    mv -f usr/bin/cygwin1.dll.new usr/bin/cygwin1.dll
+  fi
 }
 
 package_msys2-runtime() {
@@ -217,7 +348,11 @@ package_msys2-runtime() {
   mkdir -p "${pkgdir}"/usr
   cp -rf "${srcdir}"/dest/usr/bin "${pkgdir}"/usr/
   cp -rf "${srcdir}"/dest/usr/libexec "${pkgdir}"/usr/
-  rm -f "${pkgdir}"/usr/bin/msys-2.0.dbg
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    rm -f "${pkgdir}"/usr/bin/msys-2.0.dbg
+  else
+    rm -f "${pkgdir}"/usr/bin/cygwin1.dbg
+  fi
   rm -f "${pkgdir}"/usr/bin/cyglsa-config
   rm -f "${pkgdir}"/usr/bin/cyglsa.dll
   rm -f "${pkgdir}"/usr/bin/cyglsa64.dll
@@ -234,7 +369,11 @@ package_msys2-runtime-devel() {
   options=('!strip')
 
   mkdir -p "${pkgdir}"/usr/bin
-  cp -f "${srcdir}"/dest/usr/bin/msys-2.0.dbg "${pkgdir}"/usr/bin/
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    cp -f "${srcdir}"/dest/usr/bin/msys-2.0.dbg "${pkgdir}"/usr/bin/
+  else
+    cp -f "${srcdir}"/dest/usr/bin/cygwin1.dbg "${pkgdir}"/usr/bin/
+  fi
   cp -rLf "${srcdir}"/dest/usr/${CHOST}/include "${pkgdir}"/usr/
   rm -f "${pkgdir}"/usr/include/iconv.h
   rm -f "${pkgdir}"/usr/include/unctrl.h
@@ -243,6 +382,11 @@ package_msys2-runtime-devel() {
 
   cp -rLf "${srcdir}"/dest/usr/${CHOST}/lib "${pkgdir}"/usr/
 
-  # compatibility with Cygwin toolchains
-  cp "${srcdir}"/dest/usr/${CHOST}/lib/libmsys-2.0.a "${pkgdir}"/usr/lib/libcygwin.a
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    # compatibility with Cygwin toolchains
+    cp "${srcdir}"/dest/usr/${CHOST}/lib/libmsys-2.0.a "${pkgdir}"/usr/lib/libcygwin.a
+  else
+    # compatibility with Msys2 toolchains for bootstrap
+    cp "${srcdir}"/dest/usr/${CHOST}/lib/libcygwin.a "${pkgdir}"/usr/lib/libmsys-2.0.a
+  fi
 }
